In [2]:
import numpy as np

from models.logistic import sigmoid, logistic_loss, logistic_grad
from models.logistic_ridge import logistic_ridge_loss, logistic_ridge_grad
from algorithms.gradient_descent import gradient_descent

ModuleNotFoundError: No module named 'models'

In [2]:
# testing logistic.py file

# testing data
X = np.array([
    [0.0, 0.0],
    [1.0, 2.0],
    [-1.0, -20.0]
])

y = np.array([0, 1, 0])

w = np.array([0.1, -0.2])

print("Scores (X @ w):", X @ w)
print("Sigmoid:", sigmoid(X @ w))   # values should be between 0 and 1
print("Loss:", logistic_loss(w, X, y))
print("Gradient:", logistic_grad(w, X, y))

Scores (X @ w): [ 0.  -0.3  3.9]
Sigmoid: [0.5        0.42555748 0.98015969]
Loss: 1.8225140458455218
Gradient: [-0.51820074 -6.91735964]


In [3]:
# testing logistic_ridge.py file

X1 = np.array([
    [0.0, 0.0],
    [1.0, 2.0],
    [2.0, 1.0],
    [-1.0, -2.0]
])

y = np.array([0, 1, 1, 0])

# add bias column as Last column (all 1's)
ones = np.ones((X1.shape[0], 1))
X = np.hstack([X1, ones])   # shape: (4, 3)

print("X:\n", X)
print("y:", y)
print("X shape:", X.shape)

w = np.array([0.5, -0.25, 0.1])     # [w1, w2, bias]

print("w:", w)
print("w shape:", w.shape)

base_loss = logistic_loss(w, X, y)

ridge_loss_small_alpha = logistic_ridge_loss(w, X, y, alpha=0.1)
ridge_loss_large_alpha = logistic_ridge_loss(w, X, y, alpha=10.0)

print("Plain logistic loss:", base_loss)
print("Ridge logistic loss (alpha=0.1):", ridge_loss_small_alpha)
print("Ridge logistic loss (alpha=10.0):", ridge_loss_large_alpha)

X:
 [[ 0.  0.  1.]
 [ 1.  2.  1.]
 [ 2.  1.  1.]
 [-1. -2.  1.]]
y: [0 1 1 0]
X shape: (4, 3)
w: [ 0.5  -0.25  0.1 ]
w shape: (3,)
Plain logistic loss: 0.6222637602800786
Ridge logistic loss (alpha=0.1): 0.6378887602800786
Ridge logistic loss (alpha=10.0): 2.1847637602800787


In [3]:
# testing gradient_descent.py

import sys, os

print("Python executable:", sys.executable)
print("working directory:", os.getcwd())
print("sys.path:", sys.path)
for p in sys.path:
    print(" ", p)


Python executable: /Users/andimellyn/Library/Mobile Documents/com~apple~CloudDocs/andi/dsci projects/optimization project/python/.venv/bin/python
working directory: /Users/andimellyn/Library/Mobile Documents/com~apple~CloudDocs/andi/dsci projects/optimization project/python
sys.path: ['/Users/andimellyn/Library/Mobile Documents/com~apple~CloudDocs/andi/dsci projects/optimization project/python', '/Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pydev', '/Applications/PyCharm.app/Contents/plugins/python-ce/helpers/jupyter_debug', '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python39.zip', '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9', '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/lib-dynload', '', '/Users/andimellyn/Library/Mobile Documents/com~apple~CloudDocs/andi/dsci projects/optimization project/python/.venv/lib/pyth

In [2]:
import os

print("CWD:", os.getcwd())
print("Contents of CWD:", os.listdir())

CWD: /Users/andimellyn/Library/Mobile Documents/com~apple~CloudDocs/andi/dsci projects/optimization project/python
Contents of CWD: ['.DS_Store', '.venv', '.idea']
